defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":8462"

[web]
address = ":8080"

[file]

[backends]

  [backends.coursesystem]
    [backends.coursesystem.servers.server1]
    url = "http://localhost:8089"
    weight = 1
	
  [backends.calendarsystem]
    [backends.calendarsystem.servers.server1]
    url = "http://localhost:8087"
    weight = 1

  [backends.auditsystem]
    [backends.auditsystem.servers.server1]
    url = "http://localhost:8086"
    weight = 10

  [backends.rolesystem]
    [backends.rolesystem.servers.server1]
    url = "http://localhost:8084"
    weight = 1

  [backends.frontend]
    [backends.frontend.servers.server1]
    url = "http://localhost:4200"
    weight = 1

[frontends]

  [frontends.coursesystem]
    backend = "coursesystem"
    [frontends.coursesystem.routes.courses_api]
    rule = "PathPrefix:/api/courses"

  [frontends.rolesystem_users]
  backend = "rolesystem"
    [frontends.rolesystem_users.routes.user_api]
    rule = "PathPrefix:/api/users"

  [frontends.rolesystem_roles]
  backend = "rolesystem"
    [frontends.rolesystem_roles.routes.role_api]
    rule = "PathPrefix:/api/roles"

  [frontends.rolesystem_groups]
  backend = "rolesystem"
    [frontends.rolesystem_groups.routes.group_api]
    rule = "PathPrefix:/api/groups"

  [frontends.rolesystem_auth]
  backend = "rolesystem"
    [frontends.rolesystem_auth.routes.auth_api]
    rule = "PathPrefixStrip:/api/auth"

  [frontends.rolesystem_exports]
  backend = "rolesystem"
    [frontends.rolesystem_exports.routes.tokens_api]
    rule = "PathPrefix:/api/tokens"


  [frontends.auditsystem]
  backend = "auditsystem"
    [frontends.auditsystem.routes.api]
    rule = "PathPrefix:/api/auditentry"

  [frontends.calendarsystem]
  backend = "calendarsystem"
    [frontends.calendarsystem.routes.api]
    rule = "PathPrefix:/api/activities"
 
  [frontends.calendarsystem_exports]
  backend = "calendarsystem"
    [frontends.calendarsystem_exports.routes.export_api]
    rule = "PathPrefix:/api/exports"
  
  [frontends.frontend]
  backend = "frontend"
    [frontends.frontend.routes.frontend]
    rule = "PathPrefix:/"
